package org.kaudiotagger.audio.wav

enum class WavOptions {
    READ_ID3_ONLY,
    READ_INFO_ONLY,
    READ_ID3_UNLESS_ONLY_INFO,
    READ_INFO_UNLESS_ONLY_ID3,
    READ_ID3_ONLY_AND_SYNC,
    READ_ID3_UNLESS_ONLY_INFO_AND_SYNC,
    READ_INFO_UNLESS_ONLY_ID3_AND_SYNC;

}