package org.kaudiotagger.tag.id3

import org.kaudiotagger.tag.FieldKey
import java.util.*

class ID3v22Frames : ID3Frames() {

    companion object {
        val FRAME_ID_V2_ACCOMPANIMENT : String = "TP2"
        val FRAME_ID_V2_ALBUM : String = "TAL"
        val FRAME_ID_V2_ARTIST : String = "TP1"
        val FRAME_ID_V2_ATTACHED_PICTURE : String = "PIC"
        val FRAME_ID_V2_AUDIO_ENCRYPTION : String = "CRA"
        val FRAME_ID_V2_BPM : String = "TBP"
        val FRAME_ID_V2_COMMENT : String = "COM"
        val FRAME_ID_V2_COMPOSER : String = "TCM"
        val FRAME_ID_V2_CONDUCTOR : String = "TPE"
        val FRAME_ID_V2_CONTENT_GROUP_DESC : String = "TT1"
        val FRAME_ID_V2_COPYRIGHTINFO : String = "TCR"
        val FRAME_ID_V2_ENCODEDBY : String = "TEN"
        val FRAME_ID_V2_ENCRYPTED_FRAME : String = "CRM"
        val FRAME_ID_V2_EQUALISATION : String = "EQU"
        val FRAME_ID_V2_EVENT_TIMING_CODES : String = "ETC"
        val FRAME_ID_V2_FILE_TYPE : String = "TFT"
        val FRAME_ID_V2_GENERAL_ENCAPS_OBJECT : String = "GEO"
        val FRAME_ID_V2_GENRE : String = "TCO"
        val FRAME_ID_V2_HW_SW_SETTINGS : String = "TSS"
        val FRAME_ID_V2_INITIAL_KEY : String = "TKE"
        val FRAME_ID_V2_IPLS : String = "IPL"
        val FRAME_ID_V2_ISRC : String = "TRC"
        val FRAME_ID_V2_ITUNES_GROUPING : String = "GP1"
        val FRAME_ID_V2_LANGUAGE : String = "TLA"
        val FRAME_ID_V2_LENGTH : String = "TLE"
        val FRAME_ID_V2_LINKED_INFO : String = "LNK"
        val FRAME_ID_V2_LYRICIST : String = "TXT"
        val FRAME_ID_V2_MEDIA_TYPE : String = "TMT"
        val FRAME_ID_V2_MOVEMENT : String = "MVN"
        val FRAME_ID_V2_MOVEMENT_NO : String = "MV1"
        val FRAME_ID_V2_MPEG_LOCATION_LOOKUP_TABLE : String = "MLL"
        val FRAME_ID_V2_MUSIC_CD_ID : String = "MCI"
        val FRAME_ID_V2_ORGARTIST : String = "TOA"
        val FRAME_ID_V2_ORIG_FILENAME : String = "TOF"
        val FRAME_ID_V2_ORIG_LYRICIST : String = "TOL"
        val FRAME_ID_V2_ORIG_TITLE : String = "TOT"
        val FRAME_ID_V2_PLAYLIST_DELAY : String = "TDY"
        val FRAME_ID_V2_PLAY_COUNTER : String = "CNT"
        val FRAME_ID_V2_POPULARIMETER : String = "POP"
        val FRAME_ID_V2_PUBLISHER : String = "TPB"
        val FRAME_ID_V2_RECOMMENDED_BUFFER_SIZE : String = "BUF"
        val FRAME_ID_V2_RELATIVE_VOLUME_ADJUSTMENT : String = "RVA"
        val FRAME_ID_V2_REMIXED : String = "TP4"
        val FRAME_ID_V2_REVERB : String = "REV"
        val FRAME_ID_V2_SET : String = "TPA"
        val FRAME_ID_V2_SET_SUBTITLE : String = "TPS"
        val FRAME_ID_V2_SYNC_LYRIC : String = "SLT"
        val FRAME_ID_V2_SYNC_TEMPO : String = "STC"
        val FRAME_ID_V2_TDAT : String = "TDA"
        val FRAME_ID_V2_TIME : String = "TIM"
        val FRAME_ID_V2_TITLE : String = "TT2"
        val FRAME_ID_V2_TITLE_REFINEMENT : String = "TT3"
        val FRAME_ID_V2_TORY : String = "TOR"
        val FRAME_ID_V2_TRACK : String = "TRK"
        val FRAME_ID_V2_TRDA : String = "TRD"
        val FRAME_ID_V2_TSIZ : String = "TSI"
        val FRAME_ID_V2_TYER : String = "TYE"
        val FRAME_ID_V2_UNIQUE_FILE_ID : String = "UFI"
        val FRAME_ID_V2_UNSYNC_LYRICS : String = "ULT"
        val FRAME_ID_V2_URL_ARTIST_WEB : String = "WAR"
        val FRAME_ID_V2_URL_COMMERCIAL : String = "WCM"
        val FRAME_ID_V2_URL_COPYRIGHT : String = "WCP"
        val FRAME_ID_V2_URL_FILE_WEB : String = "WAF"
        val FRAME_ID_V2_URL_OFFICIAL_RADIO : String = "WRS"
        val FRAME_ID_V2_URL_PAYMENT : String = "WPAY"
        val FRAME_ID_V2_URL_PUBLISHERS : String = "WPB"
        val FRAME_ID_V2_URL_SOURCE_WEB : String = "WAS"
        val FRAME_ID_V2_USER_DEFINED_INFO : String = "TXX"
        val FRAME_ID_V2_USER_DEFINED_URL : String = "WXX"

        val FRAME_ID_V2_IS_COMPILATION : String = "TCP"
        val FRAME_ID_V2_TITLE_SORT_ORDER_ITUNES : String = "TST"
        val FRAME_ID_V2_ARTIST_SORT_ORDER_ITUNES : String = "TSP"
        val FRAME_ID_V2_ALBUM_SORT_ORDER_ITUNES : String = "TSA"
        val FRAME_ID_V2_ALBUM_ARTIST_SORT_ORDER_ITUNES : String = "TS2"
        val FRAME_ID_V2_COMPOSER_SORT_ORDER_ITUNES : String = "TSC"

        private var iD3v22Frames : ID3v22Frames

        protected val tagFieldToId3 : EnumMap<FieldKey, ID3v22FieldKey> = EnumMap(FieldKey::class.java)
    }
}